version: '4.2'
services:
    test_app:
        container_name: test_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8000
        stdin_open: true
        tty: true
        volumes:
            - .:/app
        depends_on:
            - test_db

    test_db:
        container_name: test_db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "33062:3306"
